##2026/05/13 render軌道の軽量化のためコメントアウト
#spring.application.name=OJT
#spring.datasource.url=jdbc:postgresql://localhost:5432/migre_db
#spring.datasource.username=postgres
#spring.datasource.password=pass
#spring.jpa.hibernate.ddl-auto=update
## spring.jpa.hibernate.ddl-auto=create-drop // DBをクリアしたい場合に使用
#logging.file.name=logs/application.log
#
#Hibernateのデータベース自動構築を「なし」にする（一番重い処理をスキップ！）

#2026/05/23 neonサーバー設定
#spring.jpa.hibernate.ddl-auto=none
## Tomcat（サーバー）の準備運動をサボる設定
#server.tomcat.threads.max=10
#server.tomcat.accept-count=10
## 起動時に schema.sql を実行する
#spring.sql.init.mode=always

#2026/05/27 給与計算の追加機能
# サーバーのポート番号を8081に変更（バッチとの衝突を絶対に防ぐ設定）
server.port=8081

# Tomcat（サーバー）の軽量化設定
spring.jpa.hibernate.ddl-auto=none
server.tomcat.threads.max=10
server.tomcat.accept-count=10
spring.sql.init.mode=always

# Neon DB への接続情報（バッチと同じ neondb を指定）
spring.datasource.url=jdbc:postgresql://ep-dark-block-ao8udalh-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nde1sgh6jkCA
spring.datasource.driver-class-name=org.postgresql.Driver