#2026/05/13 render軌道の軽量化のためコメントアウト
#spring.application.name=OJT
#spring.datasource.url=jdbc:postgresql://localhost:5432/migre_db
#spring.datasource.username=postgres
#spring.datasource.password=pass
#spring.jpa.hibernate.ddl-auto=update
## spring.jpa.hibernate.ddl-auto=create-drop // DBをクリアしたい場合に使用
#logging.file.name=logs/application.log

#Hibernateのデータベース自動構築を「なし」にする（一番重い処理をスキップ！）

spring.jpa.hibernate.ddl-auto=none

# Tomcat（サーバー）の準備運動をサボる設定
server.tomcat.threads.max=10
server.tomcat.accept-count=10
# 起動時に schema.sql を実行する
spring.sql.init.mode=always